package views;


import com.formdev.flatlaf.intellijthemes.FlatCyanLightIJTheme;
import views.AdminLogin;



/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author KSHPRIME
 */
public class GlobeMedHealthcare extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GlobeMedHealthcare.class.getName());

    /**
     * Creates new form GlobeMedHealthcare
     */
    public GlobeMedHealthcare() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        goToAdmin = new javax.swing.JButton();
        goToDoctor = new javax.swing.JButton();
        goToNurse = new javax.swing.JButton();
        goToPharmacist = new javax.swing.JButton();
        goToReceptionist = new javax.swing.JButton();
        goToInsuranceProvider = new javax.swing.JButton();
        logo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("GlobeMed Health Care");
        setName("GlobeMedHealthCare"); // NOI18N
        setResizable(false);

        goToAdmin.setText("Admin");
        goToAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goToAdminActionPerformed(evt);
            }
        });

        goToDoctor.setText("Doctor");

        goToNurse.setText("Nurse");

        goToPharmacist.setText("Pharmacist");

        goToReceptionist.setText("Receptionist");
        goToReceptionist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goToReceptionistActionPerformed(evt);
            }
        });

        goToInsuranceProvider.setText("Insurance Provider");

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/logo/GlobeMedLogoNBG.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 554, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(goToInsuranceProvider)
                    .addComponent(goToReceptionist)
                    .addComponent(goToPharmacist)
                    .addComponent(goToNurse)
                    .addComponent(goToDoctor)
                    .addComponent(goToAdmin))
                .addGap(81, 81, 81))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {goToAdmin, goToDoctor, goToInsuranceProvider, goToNurse, goToPharmacist, goToReceptionist});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(logo)
                .addGap(20, 20, 20))
            .addGroup(layout.createSequentialGroup()
                .addGap(126, 126, 126)
                .addComponent(goToAdmin)
                .addGap(30, 30, 30)
                .addComponent(goToDoctor)
                .addGap(30, 30, 30)
                .addComponent(goToNurse)
                .addGap(30, 30, 30)
                .addComponent(goToPharmacist)
                .addGap(30, 30, 30)
                .addComponent(goToReceptionist)
                .addGap(30, 30, 30)
                .addComponent(goToInsuranceProvider)
                .addContainerGap(126, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {goToAdmin, goToDoctor, goToInsuranceProvider, goToNurse, goToPharmacist, goToReceptionist});

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void goToAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goToAdminActionPerformed
       AdminLogin adminLogin =  new AdminLogin(this);
       adminLogin.setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_goToAdminActionPerformed

    private void goToReceptionistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goToReceptionistActionPerformed
       ReceptionLogin receptionLogin =  new ReceptionLogin(this);
       receptionLogin.setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_goToReceptionistActionPerformed

    
    public static void main(String args[]) {
     
        FlatCyanLightIJTheme.setup();
        
        GlobeMedHealthcare globeMedHealthcare =  new GlobeMedHealthcare();
        globeMedHealthcare.setVisible(true);
      
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton goToAdmin;
    private javax.swing.JButton goToDoctor;
    private javax.swing.JButton goToInsuranceProvider;
    private javax.swing.JButton goToNurse;
    private javax.swing.JButton goToPharmacist;
    private javax.swing.JButton goToReceptionist;
    private javax.swing.JLabel logo;
    // End of variables declaration//GEN-END:variables
}
